FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*
COPY storetheindex /usr/bin/storetheindex
EXPOSE 3000-3003
ENTRYPOINT ["/usr/bin/storetheindex"]
CMD ["daemon"]
